name: zentry
description: "Network scanner app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_native_splash: ^2.4.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - dotenv
    - assets/launcher-icon.png
    - assets/logo.png